management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
    jpa.hibernate:
      ddl-auto: create